# Generated by Django 5.0 on 2024-02-25 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postanalytics_content_postanalytics_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingpost',
            name='set_time',
        ),
        migrations.AddField(
            model_name='upcomingpost',
            name='date_field',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='upcomingpost',
            name='time_field',
            field=models.TimeField(default=datetime.time),
        ),
    ]
